server.port=8189
server.thread-pool-size=10

http.max-request-size-bytes=1024000
http.max-response-size-bytes=1024000
http.socket-timeout-ms=30000

db.url=jdbc:postgresql://localhost:5436/web_shop
db.username=postgres
db.password=postgres